build:
  version: "2.0"

loans:
  message: "Welcome to EBank loans related QA APIs "
  contactDetails:
    name: "Smith Doe - QA Lead"
    email: "smith@ebank.com"
  onCallSupport:
    - (555) 555-1236
    - (555) 523-1346
